server:
  port: 10001

spring:
  application:
    name: itstack-demo-ddd-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7397/eureka/

# http://localhost:10001/route-a/api/queryUserInfo?userId=111
# http://localhost:10001/route-b/api/queryUserInfo?userId=111


# 动态路由，以下配置注释；
# http://localhost:10001/route-a/api/queryUserInfo?userId=111
# http://localhost:10001/route-b/api/queryUserInfo?userId=111

zuul:
  #动态路由
  ignoredPatterns: /api/**

    #非动态路由，使用动态路由时注释以下配置
#    routes:
#      api-a:
#        path: /route-a/**
#        serviceId: itstack-demo-springcloud-feign
#      api-b:
#        path: /route-b/**
#        serviceId: itstack-demo-springcloud-ribbon
